name: notion_app
description: Notion Android App - Android-first, Token login, no AI
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  webview_flutter: ^4.10.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
